### ISSUE TITLE
Issues with spec alternative 2

### ISSUE THREAD

**Issue by anba** [tc39/proposal-object-iteration#21]
1. Calling EnumerableOwnProperties in each iteration.
It seems like that the intention for calling EnumerableOwnProperties in each iteration, is that newly added properties are picked up. But that approach only works for non-integer indexed properties, because integer-indexed properties aren't sorted by insertion order, but instead by value. For example consider:
```js
var obj = {10: 0};
var i = 0;
for (var k in Object.iterateKeys(obj)) {
  assert.sameValue(k, "10"); // |k| is always 10!
  if (i !== 10) obj[i++] = 0;
}
```

Furthermore this approach will skip properties when other properties are deleted:
```js
var obj = {a: 0, b: 0, c: 0};
for (var k of Object.iterateKeys(obj)) {
  console.log(k); // Prints "a" and then "c". "b" will be skipped!
  delete obj[k];
}
```
----

2. And calling `EnumerableOwnProperties` in each iteration will make this operation really slow, which seems to run counter to the argument given in #9.

**Comment by decompil3d** [comment]
Hi André -- thanks for your questions. I really appreciate the help on firming up this spec text. Please find responses to your concerns inline with your quotes below:

> 1. Calling EnumerableOwnProperties in each iteration.
>    It seems like that the intention for calling EnumerableOwnProperties in each iteration, is that newly added properties are picked up. But that approach only works for non-integer indexed properties, because integer-indexed properties aren't sorted by insertion order, but instead by value. For example consider:
> 
> ```js
> var obj = {10: 0};
> var i = 0;
> for (var k in Object.iterateKeys(obj)) {
>   assert.sameValue(k, "10"); // |k| is always 10!
>   if (i !== 10) obj[i++] = 0;
> }
> ```

I agree that this could possibly be a bit of a footgun. However, the numeric keys would match the behavior of arrays and the non-numeric keys would match the behavior of `Map`/`Set`. So it would at least be consistent and explainable in docs.

> Furthermore this approach will skip properties when other properties are deleted:
> 
> ```js
> var obj = {a: 0, b: 0, c: 0};
> for (var k of Object.iterateKeys(obj)) {
>   console.log(k); // Prints "a" and then "c". "b" will be skipped!
>   delete obj[k];
> }
> ```

This would match the existing behavior of array iteration. Consider the following code:

```js
const a = ['one', 'two', 'three'];
for (const v of a.values()) {
  console.log(v); // Prints 'one' and 'three' -- 'two' is skipped
  a.shift();
}
```

> 1. And calling `EnumerableOwnProperties` in each iteration will make this operation really slow, which seems to run counter to the argument given in #9.

Could an engine not just cache the response of `EnumerableOwnProperties` and re-use unless the underlying object changes? Seems like an optimization of that sort would be allowed given this spec text, and would be up to engines to implement as they'd like.

I believe that these responses should mitigate your concerns, so I'm going to close this issue. But if you disagree, please do let me know and we can discuss.
