### ISSUE TITLE
Allow passing prototype to `toObject`, drop selector functions

### ISSUE THREAD

**Issue by bergus** [tc39/proposal-object-iteration#6]
@ljharb just linked to https://github.com/tc39/proposal-object-from-entries/issues/13, which suggested having a prototype parameter for `Object.fromEntries` similar to the first parameter of `Object.create`. Given the issues with objects-as-dictionaries inheriting from `Object.prototype`, we could nicely deal with them by supporting that in `toObject`:
```js
const o = Iterator.from(…).map(…).map(… => [key, value]).toObject(null);
console.assert(Object.getPrototypeOf(o) === null);
```
This of course would mean dropping the "key selector" and "value selector" parameters, but I don't think those were a good fit anyway. Most mapping over dictionaries will be over their entries using the established key-value tuple convention, and even when reducing an iterator of something else to an object, you could just add an additional `map` step that produces the tuples. This might even be faster since only one function needs to be called per entry - assuming no inlining occurs and that escape analysis gets the array literal allocated on the stack.

**Comment by decompil3d** [comment]
Dropped `toObject` from the proposal, as `Object.fromEntries` will do the job for now. We can circle back to `toObject` later in another proposal once the Iterator Helpers proposal is finalized.
