### ISSUE TITLE
Use "Object.entries()" and "Object.fromEntries()" to implement mapping of objects

### ISSUE THREAD

**Issue by masx200** [tc39/proposal-object-iteration#9]
Use "Object.entries()" and "Object.fromEntries()" to implement mapping of objects

```js
var output=Object.fromEntries(
Object.entries(input).filter(fun).map(fun)
)
```

**Comment by decompil3d** [comment]
Thanks for your suggestion. `Object.entries` copies the object to a new array, so it is not performant nor particularly optimizable. This proposal adds a mechanism for getting an _iterator_ over the entries of an Object, which allows for in-place traversal.
